[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.63.1",
    "python-telegram-bot==20.7",
    "telegram>=0.0.1",
]
